### PR TITLE
Convert TOML to JSON5

### PR DESCRIPTION
**Pull request by mooneyme**
Converts toml to json5. There are a few remaining instances of `"toml"` or `.toml` files. These include:

- **.pre-commit-config.yaml**: "check-toml" -- not sure if we should remove/keep and/or add/replace with a json5 check
- **setup.py**: should we keep toml import?
- **dev/README.md**: any mention of toml is related to JADE
- **dsgrid/notebooks/connect_to_dsgrid_registry.ipynb** : any mention on toml is related to JADE and the cluster
- **dsgrid/utils/files.py**: `dump_data` and `load_data` keep toml as an option
- **dsgrid/utils/toml_parser.py**:  I didn't delete this. But also wasn't sure if we should have a JSON5 parser?
- **dsgrid/tests/test_files_utils.py**: keeps toml as an option
- **dsgrid/docs/_build/example_configs**: all the example configs are still toml. I didn't mess with this because we have an open PR to update the docs and example configs. 

All test data have been updated as well. These exist in related test-data PR under mm/json5_conversion branch. Standard scenarios have also been updated with the same branch name.

**Tests are currently failing, so I need to figure out what is going on there.**

### CODE REVIEW

**Comment by mooneyme** [comment]
Tests are currently failing here: https://github.com/dsgrid/dsgrid/blob/b70cbd3798b8bdc103ffba02b88c1a64c0851379/tests/conftest.py#L49

```
dsgrid.exceptions.DSGValueNotRegistered: DimensionKey(type=<DimensionType.GEOGRAPHY: 'geography'>, id='us_counties_2010_-_comstock_only__b913be60-d3da-407b-935b-6a1b8ee7d92c', version=VersionInfo(major=1, minor=0, patch=0, prerelease=None, build=None))
make script returned non-zero: 1
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/mmooney/anaconda3/envs/dsgrid/lib/python3.10/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Users/mmooney/anaconda3/envs/dsgrid/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/Users/mmooney/anaconda3/envs/dsgrid/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/Users/mmooney/anaconda3/envs/dsgrid/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/mmooney/anaconda3/envs/dsgrid/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/mmooney/anaconda3/envs/dsgrid/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/mmooney/Documents/github/github.com/dsgrid/dsgrid/tests/conftest.py", line 57, in pytest_sessionstart
INTERNALERROR>     sys.exit(1)
INTERNALERROR> SystemExit: 1
mainloop: caught unexpected SystemExit!
```

**Comment by daniel-thom** [comment]
> 

- I don't think we need to keep `toml` as a dependency. If we ever decide to use that file format, we can add it back.
- We don't use `toml_parser.py`; it can be deleted. It looks like it provides an alternate way of accessing variables and sections in a .toml. We use Pydantic for parsing dictionaries, so we don't need anything like this for JSON.

**Comment by daniel-thom** [comment]
Are you planning to update this branch also? https://github.com/dsgrid/dsgrid-project-EFS

**Comment by mooneyme** [comment]
> Are you planning to update this branch also? https://github.com/dsgrid/dsgrid-project-EFS

Should we update this repo? I sort of assumed we have abandoned this branch. Especially considering those TOMLs need to be updated to meet new expectations of the configs (beyond just the JSON5 requirement). Maybe we should just update the README of that repo with some commentary about how it is currently out of date.

**Comment by daniel-thom** [comment]
> > Are you planning to update this branch also? https://github.com/dsgrid/dsgrid-project-EFS
> 
> Should we update this repo? I sort of assumed we have abandoned this branch. Especially considering those TOMLs need to be updated to meet new expectations of the configs (beyond just the JSON5 requirement). Maybe we should just update the README of that repo with some commentary about how it is currently out of date.

I didn't know it was out-of-date. If it is, it wouldn't need many updates. Do we want to abandon it?

**Comment by mooneyme** [comment]
> https://github.com/dsgrid/dsgrid-project-EFS



> > > Are you planning to update this branch also? https://github.com/dsgrid/dsgrid-project-EFS
> > 
> > 
> > Should we update this repo? I sort of assumed we have abandoned this branch. Especially considering those TOMLs need to be updated to meet new expectations of the configs (beyond just the JSON5 requirement). Maybe we should just update the README of that repo with some commentary about how it is currently out of date.
> 
> I didn't know it was out-of-date. If it is, it wouldn't need many updates. Do we want to abandon it?

I think so. Question for @elainethale

**Comment by elainethale** [comment]
> > https://github.com/dsgrid/dsgrid-project-EFS
> 
> > > > Are you planning to update this branch also? https://github.com/dsgrid/dsgrid-project-EFS
> > > 
> > > 
> > > Should we update this repo? I sort of assumed we have abandoned this branch. Especially considering those TOMLs need to be updated to meet new expectations of the configs (beyond just the JSON5 requirement). Maybe we should just update the README of that repo with some commentary about how it is currently out of date.
> > 
> > 
> > I didn't know it was out-of-date. If it is, it wouldn't need many updates. Do we want to abandon it?
> 
> I think so. Question for @elainethale

If it's easy to update, I wouldn't abandon it.

**Comment by mooneyme** [comment]
> > > https://github.com/dsgrid/dsgrid-project-EFS
> > 
> > 
> > > > > Are you planning to update this branch also? https://github.com/dsgrid/dsgrid-project-EFS
> > > > 
> > > > 
> > > > Should we update this repo? I sort of assumed we have abandoned this branch. Especially considering those TOMLs need to be updated to meet new expectations of the configs (beyond just the JSON5 requirement). Maybe we should just update the README of that repo with some commentary about how it is currently out of date.
> > > 
> > > 
> > > I didn't know it was out-of-date. If it is, it wouldn't need many updates. Do we want to abandon it?
> > 
> > 
> > I think so. Question for @elainethale
> 
> If it's easy to update, I wouldn't abandon it.

The JSON5 conversion is relatively easy, but I don't want to spin wheels/go on a tangent testing to make sure all the JSON5 get registered properly and that all the dimension associations are accounted for correctly, etc etc. Given that, what do you think? Just make the JSON5 conversion without testing all the things?

**Comment by elainethale** [comment]
> > > > https://github.com/dsgrid/dsgrid-project-EFS
> > > 
> > > 
> > > > > > Are you planning to update this branch also? https://github.com/dsgrid/dsgrid-project-EFS
> > > > > 
> > > > > 
> > > > > Should we update this repo? I sort of assumed we have abandoned this branch. Especially considering those TOMLs need to be updated to meet new expectations of the configs (beyond just the JSON5 requirement). Maybe we should just update the README of that repo with some commentary about how it is currently out of date.
> > > > 
> > > > 
> > > > I didn't know it was out-of-date. If it is, it wouldn't need many updates. Do we want to abandon it?
> > > 
> > > 
> > > I think so. Question for @elainethale
> > 
> > 
> > If it's easy to update, I wouldn't abandon it.
> 
> The JSON5 conversion is relatively easy, but I don't want to spin wheels/go on a tangent testing to make sure all the JSON5 get registered properly and that all the dimension associations are accounted for correctly, etc etc. Given that, what do you think? Just make the JSON5 conversion without testing all the things?

Yes, make the update without testing all the things.

**Review by daniel-thom — APPROVED** [review]

**Pull request merged**
