### PR TITLE
Ll/update doc

### PR DESCRIPTION
**Pull request by lixiliu**
Completes JIRA Story DSGRID-
Closes GitHub Issue #

## Checklist

- [ ] Tests exercising the new feature or bug fix
- [ ] All tests pass
- [ ] At least one code review approval
- [ ] Consider transferring TODOs to JIRA or GitHub

### CODE REVIEW

**Comment by mooneyme** [comment]
@lixiliu is this ready for review?

**Comment by mooneyme** [comment]
Update from dsgrid meeting today: 

- I will take over this branch to add RST stuff. 
- We prefer to use standard scenarios instead of tests because it includes tomls in the format that users will find helpful as a reference for how they should configure their configs. Things in the test data repo are taken from the format registered by dsgrid and therefore includes additional things that dsgrid does during the process. It also does not include the faster way of registering a dataset in a way that also registers the dimensions. At some point in a more stable future, we may want to find a better way to incorporate these user formatted standard scenario configs in the test data, but this is not a priority right now.
-  I will check to make sure that Lixi's additions of using standard standard scenarios even though it is a private repo will work.

**Comment by lixiliu** [comment]
> Update from dsgrid meeting today:
> 
> * I will take over this branch to add RST stuff.
> * We prefer to use standard scenarios instead of tests because it includes tomls in the format that users will find helpful as a reference for how they should configure their configs. Things in the test data repo are taken from the format registered by dsgrid and therefore includes additional things that dsgrid does during the process. It also does not include the faster way of registering a dataset in a way that also registers the dimensions. At some point in a more stable future, we may want to find a better way to incorporate these user formatted standard scenario configs in the test data, but this is not a priority right now.
> * I will check to make sure that Lixi's additions of using standard standard scenarios even though it is a private repo will work.

I think Dan set up the secret access token in the last commit.

**Comment by elainethale** [comment]
@lixiliu, is this PR obsolete?

**Comment by lixiliu** [comment]
Obsolete PR

**Pull request closed without merging**
