### PR TITLE
Add project viewer Dash app

### PR DESCRIPTION
**Pull request by daniel-thom**

### CODE REVIEW

**Comment by elainethale** [comment]
@daniel-thom, I'd like to try this out myself. Is that possible at this point? I don't see instructions in the changed files.

**Comment by daniel-thom** [comment]
> @daniel-thom, I'd like to try this out myself. Is that possible at this point? I don't see instructions in the changed files.

Yes.
1. Upgrade to Python 3.10 and re-run the pip installation for dsgrid if you haven't already.
2. Follow these instructions to start the API server: https://github.com/dsgrid/dsgrid/tree/main/dev#api-server. Note the URL that it outputs.
3. Run `python dsgrid/apps/project_viewer.py`. If the default URL doesn't work, add in the value from step 2.

**Review by elainethale — COMMENTED** [review]
Additional dependencies I needed to install to run on Eagle: 
- openjdk
- dash

More strangely, while installing dash got me past this ModuleNotFoundError:

```bash
(/home/ehale/environments/dsgrid) [ehale@r3i7n35 dsgrid]$ python dsgrid/apps/project_viewer/app.py
Traceback (most recent call last):
  File "/home/ehale/dsgrid/dsgrid/apps/project_viewer/app.py", line 4, in <module>
    import dash_bootstrap_components as dbc
ModuleNotFoundError: No module named 'dash_bootstrap_components'
```

After the install I then got an ImportError:

```bash
(/home/ehale/environments/dsgrid) [ehale@r3i7n35 dsgrid]$ python dsgrid/apps/project_viewer/app.py
Traceback (most recent call last):
  File "/home/ehale/dsgrid/dsgrid/apps/project_viewer/app.py", line 3, in <module>
    from dash import Dash, dash_table, dcc, html, Input, Output, State
ImportError: cannot import name 'Input' from 'dash' (/home/ehale/environments/dsgrid/lib/python3.10/site-packages/dash/__init__.py)
```

Here's the dash portion of `pip list`:

```bash
dash                          2.6.2
dash-core-components          2.0.0
dash-html-components          2.0.0
dash-renderer                 1.1.2
dash-table                    5.0.0
```

**Comment by daniel-thom** [comment]
> Additional dependencies I needed to install to run on Eagle:
> 
> * openjdk
> * dash
> 
> More strangely, while installing dash got me past this ModuleNotFoundError:
> 
> ```shell
> (/home/ehale/environments/dsgrid) [ehale@r3i7n35 dsgrid]$ python dsgrid/apps/project_viewer/app.py
> Traceback (most recent call last):
>   File "/home/ehale/dsgrid/dsgrid/apps/project_viewer/app.py", line 4, in <module>
>     import dash_bootstrap_components as dbc
> ModuleNotFoundError: No module named 'dash_bootstrap_components'
> ```
> 
> After the install I then got an ImportError:
> 
> ```shell
> (/home/ehale/environments/dsgrid) [ehale@r3i7n35 dsgrid]$ python dsgrid/apps/project_viewer/app.py
> Traceback (most recent call last):
>   File "/home/ehale/dsgrid/dsgrid/apps/project_viewer/app.py", line 3, in <module>
>     from dash import Dash, dash_table, dcc, html, Input, Output, State
> ImportError: cannot import name 'Input' from 'dash' (/home/ehale/environments/dsgrid/lib/python3.10/site-packages/dash/__init__.py)
> ```
> 
> Here's the dash portion of `pip list`:
> 
> ```shell
> dash                          2.6.2
> dash-core-components          2.0.0
> dash-html-components          2.0.0
> dash-renderer                 1.1.2
> dash-table                    5.0.0
> ```

I forgot to include dash_bootstrap_components and just added it. I'm confused by the dash import error. Did you run `pip install -e .` after fetching updates from github? That should have installed dash.

The openjdk problem is likely tied to whether the environment variable `JAVA_HOME` is defined. Java is a prerequisite for Spark.

**Review by lixiliu — COMMENTED** [review]
Looks like this API is for viewing an existing registry and does not automatically sync with remote?

**Comment by daniel-thom** [comment]
> Looks like this API is for viewing an existing registry and does not automatically sync with remote?

That is correct. My thinking was that the people using this (us) want to inspect a local registry while debugging. We could provide a way to customize the behavior.

**Review by elainethale — APPROVED** [review]
I was able to run on my laptop. I was hoping to try out on Eagle as well, but no need to hold this up any longer.

**Pull request merged**
